// Generated by gencpp from file tesse_ros_bridge/CollisionStats.msg
// DO NOT EDIT!


#ifndef TESSE_ROS_BRIDGE_MESSAGE_COLLISIONSTATS_H
#define TESSE_ROS_BRIDGE_MESSAGE_COLLISIONSTATS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace tesse_ros_bridge
{
template <class ContainerAllocator>
struct CollisionStats_
{
  typedef CollisionStats_<ContainerAllocator> Type;

  CollisionStats_()
    : header()
    , is_collision(false)
    , object_name()  {
    }
  CollisionStats_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , is_collision(false)
    , object_name(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _is_collision_type;
  _is_collision_type is_collision;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _object_name_type;
  _object_name_type object_name;





  typedef boost::shared_ptr< ::tesse_ros_bridge::CollisionStats_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tesse_ros_bridge::CollisionStats_<ContainerAllocator> const> ConstPtr;

}; // struct CollisionStats_

typedef ::tesse_ros_bridge::CollisionStats_<std::allocator<void> > CollisionStats;

typedef boost::shared_ptr< ::tesse_ros_bridge::CollisionStats > CollisionStatsPtr;
typedef boost::shared_ptr< ::tesse_ros_bridge::CollisionStats const> CollisionStatsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tesse_ros_bridge::CollisionStats_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tesse_ros_bridge::CollisionStats_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tesse_ros_bridge::CollisionStats_<ContainerAllocator1> & lhs, const ::tesse_ros_bridge::CollisionStats_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.is_collision == rhs.is_collision &&
    lhs.object_name == rhs.object_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tesse_ros_bridge::CollisionStats_<ContainerAllocator1> & lhs, const ::tesse_ros_bridge::CollisionStats_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tesse_ros_bridge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tesse_ros_bridge::CollisionStats_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tesse_ros_bridge::CollisionStats_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tesse_ros_bridge::CollisionStats_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tesse_ros_bridge::CollisionStats_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tesse_ros_bridge::CollisionStats_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tesse_ros_bridge::CollisionStats_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tesse_ros_bridge::CollisionStats_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c6cf75271bbaaafc8a8e7fb4896411d3";
  }

  static const char* value(const ::tesse_ros_bridge::CollisionStats_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc6cf75271bbaaafcULL;
  static const uint64_t static_value2 = 0x8a8e7fb4896411d3ULL;
};

template<class ContainerAllocator>
struct DataType< ::tesse_ros_bridge::CollisionStats_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tesse_ros_bridge/CollisionStats";
  }

  static const char* value(const ::tesse_ros_bridge::CollisionStats_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tesse_ros_bridge::CollisionStats_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Collision Status and Statistics Message\n"
"# if `is_collision` is True, then `object_name` will represent the object\n"
"#   with which the agent is colliding.\n"
"\n"
"Header header\n"
"\n"
"bool is_collision\n"
"string object_name\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::tesse_ros_bridge::CollisionStats_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tesse_ros_bridge::CollisionStats_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.is_collision);
      stream.next(m.object_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CollisionStats_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tesse_ros_bridge::CollisionStats_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tesse_ros_bridge::CollisionStats_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "is_collision: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_collision);
    s << indent << "object_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.object_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TESSE_ROS_BRIDGE_MESSAGE_COLLISIONSTATS_H
