// Generated by gencpp from file tesse_ros_bridge/ObjectSpawnRequestService.msg
// DO NOT EDIT!


#ifndef TESSE_ROS_BRIDGE_MESSAGE_OBJECTSPAWNREQUESTSERVICE_H
#define TESSE_ROS_BRIDGE_MESSAGE_OBJECTSPAWNREQUESTSERVICE_H

#include <ros/service_traits.h>


#include <tesse_ros_bridge/ObjectSpawnRequestServiceRequest.h>
#include <tesse_ros_bridge/ObjectSpawnRequestServiceResponse.h>


namespace tesse_ros_bridge
{

struct ObjectSpawnRequestService
{

typedef ObjectSpawnRequestServiceRequest Request;
typedef ObjectSpawnRequestServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ObjectSpawnRequestService
} // namespace tesse_ros_bridge


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tesse_ros_bridge::ObjectSpawnRequestService > {
  static const char* value()
  {
    return "fccdcc49ae24f177c566e20905c89987";
  }

  static const char* value(const ::tesse_ros_bridge::ObjectSpawnRequestService&) { return value(); }
};

template<>
struct DataType< ::tesse_ros_bridge::ObjectSpawnRequestService > {
  static const char* value()
  {
    return "tesse_ros_bridge/ObjectSpawnRequestService";
  }

  static const char* value(const ::tesse_ros_bridge::ObjectSpawnRequestService&) { return value(); }
};


// service_traits::MD5Sum< ::tesse_ros_bridge::ObjectSpawnRequestServiceRequest> should match
// service_traits::MD5Sum< ::tesse_ros_bridge::ObjectSpawnRequestService >
template<>
struct MD5Sum< ::tesse_ros_bridge::ObjectSpawnRequestServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tesse_ros_bridge::ObjectSpawnRequestService >::value();
  }
  static const char* value(const ::tesse_ros_bridge::ObjectSpawnRequestServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tesse_ros_bridge::ObjectSpawnRequestServiceRequest> should match
// service_traits::DataType< ::tesse_ros_bridge::ObjectSpawnRequestService >
template<>
struct DataType< ::tesse_ros_bridge::ObjectSpawnRequestServiceRequest>
{
  static const char* value()
  {
    return DataType< ::tesse_ros_bridge::ObjectSpawnRequestService >::value();
  }
  static const char* value(const ::tesse_ros_bridge::ObjectSpawnRequestServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tesse_ros_bridge::ObjectSpawnRequestServiceResponse> should match
// service_traits::MD5Sum< ::tesse_ros_bridge::ObjectSpawnRequestService >
template<>
struct MD5Sum< ::tesse_ros_bridge::ObjectSpawnRequestServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tesse_ros_bridge::ObjectSpawnRequestService >::value();
  }
  static const char* value(const ::tesse_ros_bridge::ObjectSpawnRequestServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tesse_ros_bridge::ObjectSpawnRequestServiceResponse> should match
// service_traits::DataType< ::tesse_ros_bridge::ObjectSpawnRequestService >
template<>
struct DataType< ::tesse_ros_bridge::ObjectSpawnRequestServiceResponse>
{
  static const char* value()
  {
    return DataType< ::tesse_ros_bridge::ObjectSpawnRequestService >::value();
  }
  static const char* value(const ::tesse_ros_bridge::ObjectSpawnRequestServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TESSE_ROS_BRIDGE_MESSAGE_OBJECTSPAWNREQUESTSERVICE_H
