// Generated by gencpp from file tesse_ros_bridge/ObjectSpawnRequestServiceRequest.msg
// DO NOT EDIT!


#ifndef TESSE_ROS_BRIDGE_MESSAGE_OBJECTSPAWNREQUESTSERVICEREQUEST_H
#define TESSE_ROS_BRIDGE_MESSAGE_OBJECTSPAWNREQUESTSERVICEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace tesse_ros_bridge
{
template <class ContainerAllocator>
struct ObjectSpawnRequestServiceRequest_
{
  typedef ObjectSpawnRequestServiceRequest_<ContainerAllocator> Type;

  ObjectSpawnRequestServiceRequest_()
    : id(0)
    , pose()
    , params()  {
    }
  ObjectSpawnRequestServiceRequest_(const ContainerAllocator& _alloc)
    : id(0)
    , pose(_alloc)
    , params(_alloc)  {
  (void)_alloc;
    }



   typedef int8_t _id_type;
  _id_type id;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _params_type;
  _params_type params;





  typedef boost::shared_ptr< ::tesse_ros_bridge::ObjectSpawnRequestServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tesse_ros_bridge::ObjectSpawnRequestServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectSpawnRequestServiceRequest_

typedef ::tesse_ros_bridge::ObjectSpawnRequestServiceRequest_<std::allocator<void> > ObjectSpawnRequestServiceRequest;

typedef boost::shared_ptr< ::tesse_ros_bridge::ObjectSpawnRequestServiceRequest > ObjectSpawnRequestServiceRequestPtr;
typedef boost::shared_ptr< ::tesse_ros_bridge::ObjectSpawnRequestServiceRequest const> ObjectSpawnRequestServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tesse_ros_bridge::ObjectSpawnRequestServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tesse_ros_bridge::ObjectSpawnRequestServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tesse_ros_bridge::ObjectSpawnRequestServiceRequest_<ContainerAllocator1> & lhs, const ::tesse_ros_bridge::ObjectSpawnRequestServiceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.pose == rhs.pose &&
    lhs.params == rhs.params;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tesse_ros_bridge::ObjectSpawnRequestServiceRequest_<ContainerAllocator1> & lhs, const ::tesse_ros_bridge::ObjectSpawnRequestServiceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tesse_ros_bridge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tesse_ros_bridge::ObjectSpawnRequestServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tesse_ros_bridge::ObjectSpawnRequestServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tesse_ros_bridge::ObjectSpawnRequestServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tesse_ros_bridge::ObjectSpawnRequestServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tesse_ros_bridge::ObjectSpawnRequestServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tesse_ros_bridge::ObjectSpawnRequestServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tesse_ros_bridge::ObjectSpawnRequestServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c47c05d4acb39eb4b0796232e4b97a9a";
  }

  static const char* value(const ::tesse_ros_bridge::ObjectSpawnRequestServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc47c05d4acb39eb4ULL;
  static const uint64_t static_value2 = 0xb0796232e4b97a9aULL;
};

template<class ContainerAllocator>
struct DataType< ::tesse_ros_bridge::ObjectSpawnRequestServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tesse_ros_bridge/ObjectSpawnRequestServiceRequest";
  }

  static const char* value(const ::tesse_ros_bridge::ObjectSpawnRequestServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tesse_ros_bridge::ObjectSpawnRequestServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "## Object Spawn Request Service\n"
"\n"
"# Request fields\n"
"int8 id  # integer id of object class\n"
"geometry_msgs/Pose pose\n"
"float64[] params\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::tesse_ros_bridge::ObjectSpawnRequestServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tesse_ros_bridge::ObjectSpawnRequestServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.pose);
      stream.next(m.params);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectSpawnRequestServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tesse_ros_bridge::ObjectSpawnRequestServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tesse_ros_bridge::ObjectSpawnRequestServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int8_t>::stream(s, indent + "  ", v.id);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "params[]" << std::endl;
    for (size_t i = 0; i < v.params.size(); ++i)
    {
      s << indent << "  params[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.params[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TESSE_ROS_BRIDGE_MESSAGE_OBJECTSPAWNREQUESTSERVICEREQUEST_H
