// Generated by gencpp from file tesse_ros_bridge/RepositionRequestService.msg
// DO NOT EDIT!


#ifndef TESSE_ROS_BRIDGE_MESSAGE_REPOSITIONREQUESTSERVICE_H
#define TESSE_ROS_BRIDGE_MESSAGE_REPOSITIONREQUESTSERVICE_H

#include <ros/service_traits.h>


#include <tesse_ros_bridge/RepositionRequestServiceRequest.h>
#include <tesse_ros_bridge/RepositionRequestServiceResponse.h>


namespace tesse_ros_bridge
{

struct RepositionRequestService
{

typedef RepositionRequestServiceRequest Request;
typedef RepositionRequestServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RepositionRequestService
} // namespace tesse_ros_bridge


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tesse_ros_bridge::RepositionRequestService > {
  static const char* value()
  {
    return "b66f4c8c2fa81b98544cf0f3e10950ee";
  }

  static const char* value(const ::tesse_ros_bridge::RepositionRequestService&) { return value(); }
};

template<>
struct DataType< ::tesse_ros_bridge::RepositionRequestService > {
  static const char* value()
  {
    return "tesse_ros_bridge/RepositionRequestService";
  }

  static const char* value(const ::tesse_ros_bridge::RepositionRequestService&) { return value(); }
};


// service_traits::MD5Sum< ::tesse_ros_bridge::RepositionRequestServiceRequest> should match
// service_traits::MD5Sum< ::tesse_ros_bridge::RepositionRequestService >
template<>
struct MD5Sum< ::tesse_ros_bridge::RepositionRequestServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tesse_ros_bridge::RepositionRequestService >::value();
  }
  static const char* value(const ::tesse_ros_bridge::RepositionRequestServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tesse_ros_bridge::RepositionRequestServiceRequest> should match
// service_traits::DataType< ::tesse_ros_bridge::RepositionRequestService >
template<>
struct DataType< ::tesse_ros_bridge::RepositionRequestServiceRequest>
{
  static const char* value()
  {
    return DataType< ::tesse_ros_bridge::RepositionRequestService >::value();
  }
  static const char* value(const ::tesse_ros_bridge::RepositionRequestServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tesse_ros_bridge::RepositionRequestServiceResponse> should match
// service_traits::MD5Sum< ::tesse_ros_bridge::RepositionRequestService >
template<>
struct MD5Sum< ::tesse_ros_bridge::RepositionRequestServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tesse_ros_bridge::RepositionRequestService >::value();
  }
  static const char* value(const ::tesse_ros_bridge::RepositionRequestServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tesse_ros_bridge::RepositionRequestServiceResponse> should match
// service_traits::DataType< ::tesse_ros_bridge::RepositionRequestService >
template<>
struct DataType< ::tesse_ros_bridge::RepositionRequestServiceResponse>
{
  static const char* value()
  {
    return DataType< ::tesse_ros_bridge::RepositionRequestService >::value();
  }
  static const char* value(const ::tesse_ros_bridge::RepositionRequestServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TESSE_ROS_BRIDGE_MESSAGE_REPOSITIONREQUESTSERVICE_H
