// Generated by gencpp from file tesse_ros_bridge/SceneRequestServiceRequest.msg
// DO NOT EDIT!


#ifndef TESSE_ROS_BRIDGE_MESSAGE_SCENEREQUESTSERVICEREQUEST_H
#define TESSE_ROS_BRIDGE_MESSAGE_SCENEREQUESTSERVICEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tesse_ros_bridge
{
template <class ContainerAllocator>
struct SceneRequestServiceRequest_
{
  typedef SceneRequestServiceRequest_<ContainerAllocator> Type;

  SceneRequestServiceRequest_()
    : id(0)  {
    }
  SceneRequestServiceRequest_(const ContainerAllocator& _alloc)
    : id(0)  {
  (void)_alloc;
    }



   typedef int8_t _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::tesse_ros_bridge::SceneRequestServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tesse_ros_bridge::SceneRequestServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SceneRequestServiceRequest_

typedef ::tesse_ros_bridge::SceneRequestServiceRequest_<std::allocator<void> > SceneRequestServiceRequest;

typedef boost::shared_ptr< ::tesse_ros_bridge::SceneRequestServiceRequest > SceneRequestServiceRequestPtr;
typedef boost::shared_ptr< ::tesse_ros_bridge::SceneRequestServiceRequest const> SceneRequestServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tesse_ros_bridge::SceneRequestServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tesse_ros_bridge::SceneRequestServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tesse_ros_bridge::SceneRequestServiceRequest_<ContainerAllocator1> & lhs, const ::tesse_ros_bridge::SceneRequestServiceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tesse_ros_bridge::SceneRequestServiceRequest_<ContainerAllocator1> & lhs, const ::tesse_ros_bridge::SceneRequestServiceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tesse_ros_bridge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tesse_ros_bridge::SceneRequestServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tesse_ros_bridge::SceneRequestServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tesse_ros_bridge::SceneRequestServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tesse_ros_bridge::SceneRequestServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tesse_ros_bridge::SceneRequestServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tesse_ros_bridge::SceneRequestServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tesse_ros_bridge::SceneRequestServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7d504299943ad968aabe3de24053d208";
  }

  static const char* value(const ::tesse_ros_bridge::SceneRequestServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7d504299943ad968ULL;
  static const uint64_t static_value2 = 0xaabe3de24053d208ULL;
};

template<class ContainerAllocator>
struct DataType< ::tesse_ros_bridge::SceneRequestServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tesse_ros_bridge/SceneRequestServiceRequest";
  }

  static const char* value(const ::tesse_ros_bridge::SceneRequestServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tesse_ros_bridge::SceneRequestServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "## Scene Change Request Service\n"
"\n"
"# Request fields\n"
"int8 id  # integer id of scene request\n"
;
  }

  static const char* value(const ::tesse_ros_bridge::SceneRequestServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tesse_ros_bridge::SceneRequestServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SceneRequestServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tesse_ros_bridge::SceneRequestServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tesse_ros_bridge::SceneRequestServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int8_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TESSE_ROS_BRIDGE_MESSAGE_SCENEREQUESTSERVICEREQUEST_H
