// Generated by gencpp from file tesse_ros_bridge/SceneRequestServiceResponse.msg
// DO NOT EDIT!


#ifndef TESSE_ROS_BRIDGE_MESSAGE_SCENEREQUESTSERVICERESPONSE_H
#define TESSE_ROS_BRIDGE_MESSAGE_SCENEREQUESTSERVICERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tesse_ros_bridge
{
template <class ContainerAllocator>
struct SceneRequestServiceResponse_
{
  typedef SceneRequestServiceResponse_<ContainerAllocator> Type;

  SceneRequestServiceResponse_()
    : success(false)  {
    }
  SceneRequestServiceResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::tesse_ros_bridge::SceneRequestServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tesse_ros_bridge::SceneRequestServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SceneRequestServiceResponse_

typedef ::tesse_ros_bridge::SceneRequestServiceResponse_<std::allocator<void> > SceneRequestServiceResponse;

typedef boost::shared_ptr< ::tesse_ros_bridge::SceneRequestServiceResponse > SceneRequestServiceResponsePtr;
typedef boost::shared_ptr< ::tesse_ros_bridge::SceneRequestServiceResponse const> SceneRequestServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tesse_ros_bridge::SceneRequestServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tesse_ros_bridge::SceneRequestServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tesse_ros_bridge::SceneRequestServiceResponse_<ContainerAllocator1> & lhs, const ::tesse_ros_bridge::SceneRequestServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tesse_ros_bridge::SceneRequestServiceResponse_<ContainerAllocator1> & lhs, const ::tesse_ros_bridge::SceneRequestServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tesse_ros_bridge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tesse_ros_bridge::SceneRequestServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tesse_ros_bridge::SceneRequestServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tesse_ros_bridge::SceneRequestServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tesse_ros_bridge::SceneRequestServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tesse_ros_bridge::SceneRequestServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tesse_ros_bridge::SceneRequestServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tesse_ros_bridge::SceneRequestServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::tesse_ros_bridge::SceneRequestServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::tesse_ros_bridge::SceneRequestServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tesse_ros_bridge/SceneRequestServiceResponse";
  }

  static const char* value(const ::tesse_ros_bridge::SceneRequestServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tesse_ros_bridge::SceneRequestServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"# Response fields\n"
"bool success  # true if scene change was completed without exception, false otw\n"
"\n"
;
  }

  static const char* value(const ::tesse_ros_bridge::SceneRequestServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tesse_ros_bridge::SceneRequestServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SceneRequestServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tesse_ros_bridge::SceneRequestServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tesse_ros_bridge::SceneRequestServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TESSE_ROS_BRIDGE_MESSAGE_SCENEREQUESTSERVICERESPONSE_H
