(cl:defpackage tesse_ros_bridge-srv
  (:use )
  (:export
   "OBJECTSPAWNREQUESTSERVICE"
   "<OBJECTSPAWNREQUESTSERVICE-REQUEST>"
   "OBJECTSPAWNREQUESTSERVICE-REQUEST"
   "<OBJECTSPAWNREQUESTSERVICE-RESPONSE>"
   "OBJECTSPAWNREQUESTSERVICE-RESPONSE"
   "REPOSITIONREQUESTSERVICE"
   "<REPOSITIONREQUESTSERVICE-REQUEST>"
   "REPOSITIONREQUESTSERVICE-REQUEST"
   "<REPOSITIONREQUESTSERVICE-RESPONSE>"
   "REPOSITIONREQUESTSERVICE-RESPONSE"
   "SCENEREQUESTSERVICE"
   "<SCENEREQUESTSERVICE-REQUEST>"
   "SCENEREQUESTSERVICE-REQUEST"
   "<SCENEREQUESTSERVICE-RESPONSE>"
   "SCENEREQUESTSERVICE-RESPONSE"
  ))

